kubernetes-sigs/application

README.md

The attempt here is to describe a human readable value proposition
cc @ant31

Updating the description with a value prop in the readme

---

Gopkg.lock
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/config/config.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/controller.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/controller_test.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/eventhandlers/eventhandlers.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/eventhandlers/eventhandlers_test.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/example_controller_test.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/example_watchandhandleevents_test.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/example_watchandmap_test.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/controller/types/types.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/gen/apis/doc.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/gen/apis/example_test.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/gen/controller/doc.go
vendor/github.com/kubernetes-sigs/kubebuilder/pkg/gen/controller/example_test.go

@kow3ns 
```
$ dep ensure
$ kubebuilder update vendor 
```

Update dependencies and vendor directory

---

README.md

- Fix non-standard markup
- Correct spelling
- Add links to some key concepts

fix markup & spelling. add links

---

e2e/e2e-prow.sh

Update e2e-prow.sh to change target test repo

---

README.md

The componentKinds live under spec, not metadata

Fixed the example app with fixes from PR#4

---

README.md

Also fix the controller image build instructions.

Fix some typos in the README.

---

docs/example.yaml

fix invalid example.yaml

---

README.md

fixes a couple of typos in the main readme.md file

doc(readme): fixes a couple of typos

---

pkg/controller/application/application_controller.go

This is useful for people who wants to use the App CRD as part of other projects/products 
@kow3ns 
@barney-s

Define the names of the label keys as constants

---

pkg/apis/app/v1beta1/status.go

status for more core types

---

Makefile
config/rbac/rbac_role.yaml

- adjust roles since Application  needs to list and add ownerref to arbitrary resources
- add make undeploy target.
ps: we still need to change the image 
diff --git a/config/default/manager_image_patch.yaml b/config/default/manager_image_patch.yaml                                                                                                                                                
index fcbf39dc..3c7f3e27 100644                                                                                                                                                                                                               
--- a/config/default/manager_image_patch.yaml …

Adjust roles for deploying application controller

---

OWNERS_ALIASES

Adding barney-s to approvers to help with the project velocity. 
We are planning a re arch of the controller to bring it to latest kubebuilder version
Setup travis etc.

Adding barney-s to approvers

---

Dockerfile.ppc64le

Here's a support of ppc64le. Please help to review and commit. thanks.
/cc @jinchihe, @hougangliu

Give support of ppc64le

---

OWNERS_ALIASES

Adding myself to as an approver to help reviewing issues and PR. 
I'll update progress on sig-apps and ping others maintainers when needed before approving a PR.

Add ant31 to the approvers list

---

api/v1beta1/application_types.go
config/crd/bases/app.k8s.io_applications.yaml

Add protocol fields to Service and Ingress info items

---

README.md

Add more instruction around CRD installation

More update to the README file

---

CONTRIBUTING.md
docs/develop.md
docs/quickstart.md

Fix review comments from https://github.com/kubernetes-sigs/application/pull/160

Fix doc broken links

---

config/rbac/role.yaml
controllers/application_controller.go

As a follow-up of #155, the file is now generated and annotations should have been added. 
cc @nan-yu

Add rbac generation rules to access other resources

---

Dockerfile
Makefile
config/default/kustomization.yaml
config/default/manager_webhook_patch.yaml
config/manager/manager.yaml
config/rbac/auth_proxy_service.yaml
config/rbac/role.yaml
config/rbac/role_binding.yaml
docs/develop.md
e2e/main_test.go
main.go

Rename manager to kube-app-manager

---

controllers/application_controller.go

trivial fix.
Running make fixed this.

go fmt fix
