README.md

The acronym CRD is no longer defined in the document. The original version included defined the acronym the first time CRD (Custom Resource Definition) was used in the document, which is customary.

Add back definition of CRD acronym

---

README.md
pkg/apis/app/v1beta1/application_types.go

This is an updated version of https://github.com/kubernetes-sigs/application/pull/48 that lives in my own fork rather than a fork in the upstream repo.
Addressed the comments:
1. Dropped suggestion from the decription field.
1. Made the encouragement for explicit.
@mattfarina (github doesn't let me add you to reviewers)

Encouraging using markdown for notes

---

README.md

Application CRD has to be created before we can create Application objects. The section lists specifications of Application objects, not Application CRD. They are different.

Clarify that Application CRD and object are different

---

pkg/controller/application/application_controller_test.go

Remove generated test file.
Basic skeleton that passes. 
Will need to add e2e tests instead.
fixes #88

prune generated test file

---

README.md
pkg/apis/app/v1beta1/application.go
pkg/apis/app/v1beta1/application_types.go
pkg/component/component_test.go
pkg/component/types.go
pkg/genericreconciler/genericreconciler.go

When addOwnerRef is true, inject appcrd as one of the owners for the matching objects
The .controller field of the owner ref is set to false.
fixes https://github.com/kubernetes-sigs/application/issues/86

Add 'addOwnerRef' flag to the spec.

---

pkg/genericreconciler/genericreconciler.go

Currently any error listing is bubbled up and loop is aborted.
This fix logs KindMatchError (user input error) and does not abort the loop.
This is to make the controller resilient to usererrors while allowing functionality to prevail.
Fixes #105

Make KindMatchError (result of bad GVK config in crd) less fatal

---

pkg/apis/app/v1beta1/status.go

Sort the componentlist objects in a stable way so that the status converges.
this avoids the controller from looping because it observes changes in application cr since the order changes

sort the status componentlist so that it converges stably

---

pkg/genericreconciler/genericreconciler.go

Problem:
related to GoogleCloudPlatform/click-to-deploy#592
Issue:
1. An application was deployed from market place - application crd, sts, configmaps, ...
2. The application controller deleted a config map a few seconds later
3. This was an intermittent problem
Root Cause:
The ObserverAndMutate() code does this:
1. observed <- observe resources from cluster
2. expected <- controller's mutate(observed) [in this controller, expected = observed]
3. observed <- observe resources from cluster
4. reconcile expected and observed => observed between 1, 3 differs thereby differs from expected.
As part of reconcile we delete objects that are in observed but not in expected.
Solution:
The logic to observe after a mutation does not apply to this controller. It was from a different code.
We can …

Avoid observe after mutating

---

controllers/application_controller_test.go
main.go

Build was failing with 'err' undefined.
Fix linting

Fix build error

---

docs/examples/wordpress/application.yaml
e2e/test_e2e.sh
e2e/wordpress_test.go
hack/scripts/common.sh

- add E2E test for wordpress example. It is now disabled in travis because the controller image is not available to the kind cluster
- update kubernetes to version 1.16.4

Add e2e test for the wordpress example

---

api/v1beta1/application_types.go
config/crd/bases/app.k8s.io_applications.yaml
controllers/application_controller.go
controllers/application_controller_test.go
e2e/test_e2e.sh
hack/scripts/common.sh

The status subresource was not added to the CRD definition, which makes
`r.Client.Status().Update(ctx, original)` return a 404 error with the
following message:
```
failed to update status of Application default/xxx:
applications.app.k8s.io "xxx" not found
```
This commit add the status subresource to the CRD definition.
It also moves application observedGeneration before we check whether
there are any changs to the status, which makes it possibly return
early.

Add the status subresource to the application CRD

---

Makefile

$(TOOLBIN)/kustomize was refactored to use the absolute path.

Update kustomize tool path

---

README.md
config/samples/app_v1beta1_application.yaml
controllers/application_controller_test.go
docs/examples/wordpress/application.yaml
e2e/wordpress_test.go

The group of Service can be either "v1" or empty (""), but not "core",
so as other resources (ConfigMap, Pod, Secret, PersistentVolumeClaim and
etc.).

Update the group of Service in the examples and tests

---

config/rbac/role.yaml

The application controller will list and update resources.
Without the access, the controller will fail to fetch or update the
resources with the following errors:
```
controllers.Application	deployments.apps is forbidden: User "system:serviceaccount:application-system:default" cannot list resource "deployments" in API group "apps" in the namespace "default"
```

Grant application-manager access to all resources

---

.travis.yml
Makefile

Golangci-lint failed intermittently on travis Mac OS.
https://travis-ci.org/kubernetes-sigs/application/jobs/650588417?utm_medium=notification&utm_source=github_status
https://travis-ci.org/kubernetes-sigs/application/builds/650452790?utm_source=github_status&utm_medium=notification
....
The speed of the latest version seems to increase a lot per
https://github.com/golangci/golangci-lint/issues/685#issuecomment-541886167.

Update golangci-lint to the latest version

---

Makefile
api/v1beta1/application_types.go
config/crd/bases/app.k8s.io_applications.yaml
controllers/application_controller.go

fixes #163 
```
$ kubectl get  applications
NAME           TYPE        VERSION   OWNER   READY   AGE
wordpress-01   wordpress   4.9.4     true    5/5     6d13h
```
Also add application as part of the 'all' category and short-name 'app'

Add columns printer for kubectl

---

config/prometheus/kustomization.yaml
config/prometheus/kustomizeconfig.yaml
config/prometheus/monitor.yaml

ServiceMonitor has a Label selector that wasn't updated after kustomize transformations.

Add  kustomize config for prometheus ServiceMonitor

---

controllers/status.go
docs/examples/wordpress/webserver.yaml
e2e/main_test.go
e2e/resources/withcrd/base/service.yaml

This commit follows the documentation to compute the resource status:
https://docs.google.com/document/d/1RAPC5-LCb_VBpzvbpCLn8Z-7eilRAWmO0RGbVuChhPc/edit#heading=h.rqs3jxocuzbw
Instead of extracting fields from unstructured, it converts unstructured to corresponding object first.

Update the way to compute resource status

---

controllers/application_controller.go
controllers/condition.go

Fixes https://github.com/kubernetes-sigs/application/issues/183

Mark aggregated condition ready only when No error happened

---

e2e/main_test.go
e2e/resources/app-crd-v0.8.0.yaml
e2e/testutil/customresource.go

The test is to guarantee that existing application CR objects also work with new Application CRD and controller.
The old_app_crd.yaml was from version `v0.8.0`, which was released before we migrated to kubebuild 2.x.

Add a e2e test case for backward compatibility test

---

controllers/application_controller.go
controllers/application_controller_test.go

If no spec.selector.matchingLabels is set, the application controller
crashes due to a nil pointer. This commit fixes the issue by checking if
selector is nil before getting the matching labels from it. If no
selector is set, it matches all objects.

Fix the controller crashing issue

---

OWNERS_ALIASES

For kubernetes/org#2013
As a part of cleaning up inactive members (who haven't been active since
the release of v1.11) from OWNERS, this commit removes adamreese from
the OWNERS_ALIASES file.
/assign @prydonius @janetkuo 
cc @mrbobbytables @adamreese

Remove inactive members from OWNERS

---

docs/examples/wordpress/kustomization.yaml

The values for secretGenereator in the kuztomization.yaml seemed to need a String vs array. Updated it to use   env: path   vs   envs: -path

Fix for example kustomize secretGenerator from envs to env

---

controllers/status.go

**What type of PR is this?**
/kind bug
**What this PR does / why we need it**:
When calculating the status of a loadbalancer service, it returns InProgress, but my service is Ready. the reason is function isEmpty returns false.
```
isEmpty(service.Spec.ClusterIP)
```
But, If the service type is loadBalancer, the clusterIP should not be empty, this pr fix it
**Which issue(s) this PR fixes**:
Fixes #226
**Special notes for your reviewer**:
**Does this PR introduce a user-facing change?**:
```release-note
NONE
```

fix: the service status of the loadbalancer type is incorrectly calculated
